import { useMemo, useState } from 'react';
import { detectedRuleReferences } from '../../rules/ruleRegistry';
import { useRulesCrossLink } from '../../rules/useRulesCrossLink';
import type { SemanticRuleReference } from '../../types/models';

export default function RuleLinkInspector({ text, references, onChange }: { text: string; references: SemanticRuleReference[]; onChange: (references: SemanticRuleReference[]) => void }) {
  const { registry, openRule } = useRulesCrossLink();
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [manualText, setManualText] = useState('');
  const [manualQuery, setManualQuery] = useState('');
  const suggestions = useMemo(() => registry ? detectedRuleReferences(text, registry).filter((suggestion) => !references.some((reference) => reference.ruleId === suggestion.ruleId && reference.text?.toLocaleLowerCase() === suggestion.text?.toLocaleLowerCase())) : [], [references, registry, text]);
  const manualMatches = useMemo(() => {
    const query = manualQuery.trim().toLocaleLowerCase();
    if (!query) return [];
    return registry?.entries.filter((entry) => [entry.canonicalName, entry.category, ...entry.aliases.map(({ text: alias }) => alias)].some((value) => value.toLocaleLowerCase().includes(query))).slice(0, 8) ?? [];
  }, [manualQuery, registry]);
  if (!registry) return null;
  return <div className="mt-3 rounded-lg border border-violet-400/15 bg-violet-500/[0.04] p-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-black uppercase tracking-wider text-violet-300">Official Rule Links</div><div className="mt-0.5 text-[10px] text-slate-600">Stored separately; your wording stays unchanged.</div></div><button type="button" onClick={() => setShowSuggestions((value) => !value)} className="rounded-lg border border-violet-400/20 bg-violet-500/10 px-2.5 py-1.5 text-[10px] font-black text-violet-100">{showSuggestions ? 'Hide suggestions' : 'Detect Rules References'}</button></div>
    {references.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{references.map((reference, index) => { const entry = registry.byID.get(reference.ruleId); return <span key={`${reference.ruleId}-${reference.text ?? ''}-${index}`} className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px] font-bold ${reference.disabled ? 'border-slate-500/20 bg-slate-800/60 text-slate-400' : entry ? 'border-emerald-400/20 bg-emerald-500/10 text-emerald-100' : 'border-amber-400/20 bg-amber-500/10 text-amber-100'}`}><button type="button" disabled={!entry} onClick={() => reference.disabled ? onChange(references.map((candidate, current) => current === index ? { ...candidate, disabled: false } : candidate)) : openRule(reference.ruleId, { sourceVersion: reference.rulesVersion })} className="font-bold disabled:cursor-default">{reference.disabled ? `↺ Plain text: ${reference.text ?? entry?.canonicalName ?? reference.ruleId}` : entry ? `✓ ${reference.text ?? entry.canonicalName} → ${entry.canonicalName}` : 'Rule unavailable'}</button><button type="button" aria-label={`Remove ${entry?.canonicalName ?? reference.ruleId} rule link`} onClick={() => onChange(reference.disabled ? references.filter((_, current) => current !== index) : references.map((candidate, current) => current === index ? { ...candidate, disabled: true } : candidate))} className="ml-1 opacity-60 hover:opacity-100">×</button></span>; })}</div>}
    {showSuggestions && <div className="mt-3 border-t border-white/5 pt-3">{suggestions.length > 0 ? <div className="space-y-2">{suggestions.map((suggestion) => { const entry = registry.byID.get(suggestion.ruleId); return entry ? <div key={`${suggestion.ruleId}-${suggestion.text}`} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-900 p-2 text-[10px]"><span className="font-bold text-slate-300">{suggestion.text} → {entry.canonicalName}</span><span className="flex gap-1"><button type="button" onClick={() => onChange([...references, { ...suggestion, rulesVersion: registry.version }])} className="rounded bg-emerald-700/70 px-2 py-1 font-black text-white">Approve</button><button type="button" onClick={() => onChange([...references, { ...suggestion, disabled: true, rulesVersion: registry.version }])} className="rounded bg-slate-700 px-2 py-1 font-black text-slate-200">Keep plain</button></span></div> : null; })}</div> : <p className="text-[10px] text-slate-600">No additional high-confidence rule terms detected.</p>}
      <div className="mt-3 rounded-lg border border-white/5 bg-slate-950/40 p-2"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Manual link</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><input value={manualText} onChange={(event) => setManualText(event.target.value)} placeholder="Exact words in description" className="rounded-lg border border-white/10 bg-slate-900 px-2 py-1.5 text-xs text-slate-200" /><input value={manualQuery} onChange={(event) => setManualQuery(event.target.value)} placeholder="Search official rules" className="rounded-lg border border-white/10 bg-slate-900 px-2 py-1.5 text-xs text-slate-200" /></div>{manualMatches.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{manualMatches.map((entry) => <button type="button" key={entry.id} disabled={!manualText || !text.includes(manualText)} onClick={() => { onChange([...references, { ruleId: entry.id, text: manualText, rulesVersion: registry.version }]); setManualText(''); setManualQuery(''); }} className="rounded bg-violet-700/70 px-2 py-1 text-[10px] font-bold text-white disabled:opacity-30">Link to {entry.canonicalName}</button>)}</div>}<p className="mt-1 text-[9px] text-slate-600">Enter the exact selected wording, then choose its official rule. The description itself is never rewritten.</p></div>
    </div>}
  </div>;
}
