import { useCampaignStore } from '../../store/campaignStore';

interface HomebrewViewProps {
  onCreateMonster: () => void;
  onCreateItem: () => void;
  onOpenMonster: (id: string) => void;
  onOpenItem: (id: string) => void;
}

export default function HomebrewView({ onCreateMonster, onCreateItem, onOpenMonster, onOpenItem }: HomebrewViewProps) {
  const { campaignData } = useCampaignStore();
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8"><header><p className="theme-accent-text text-xs font-black uppercase tracking-[0.24em]">Library Workshop</p><h1 className="mt-1 text-3xl font-black text-white sm:text-4xl">Homebrew</h1><p className="mt-2 max-w-3xl text-slate-400">Your custom monsters and items live here while continuing to work everywhere they already do: encounter building, combat, inventories, and global search.</p></header>
    <div className="grid gap-4 md:grid-cols-2"><button type="button" onClick={onCreateMonster} className="rounded-2xl border border-emerald-400/20 bg-emerald-950/20 p-5 text-left hover:bg-emerald-500/10"><span className="text-3xl" aria-hidden="true">🐾</span><h2 className="mt-3 text-xl font-black text-white">Create Custom Monster</h2><p className="mt-1 text-sm text-slate-400">Open the full monster builder with DC20 baselines and traits.</p><span className="mt-4 block text-xs font-black uppercase tracking-wider text-emerald-300">Start building →</span></button><button type="button" onClick={onCreateItem} className="rounded-2xl border border-amber-400/20 bg-amber-950/20 p-5 text-left hover:bg-amber-500/10"><span className="text-3xl" aria-hidden="true">🎒</span><h2 className="mt-3 text-xl font-black text-white">Create Custom Item</h2><p className="mt-1 text-sm text-slate-400">Create an item and route its sheet effects where appropriate.</p><span className="mt-4 block text-xs font-black uppercase tracking-wider text-amber-300">Start building →</span></button></div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-slate-900/70 p-4 sm:p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-white">Custom Monsters</h2><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-bold text-emerald-200">{campaignData.customMonsters.length}</span></div><div className="mt-4 space-y-2">{campaignData.customMonsters.map((monster) => <button type="button" key={monster.id} onClick={() => onOpenMonster(monster.id)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-white/5 bg-slate-950/45 p-3 text-left hover:border-emerald-400/25"><span><span className="block font-black text-slate-100">{monster.name || 'Unnamed Monster'}</span><span className="mt-1 block text-xs text-slate-500">Level {monster.level} • {monster.type} {monster.role}</span></span><span className="text-emerald-300">Open →</span></button>)}{campaignData.customMonsters.length === 0 && <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">No custom monsters yet.</p>}</div></section>
      <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-4 sm:p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-white">Custom Items</h2><span className="rounded-full bg-amber-500/10 px-2 py-1 text-xs font-bold text-amber-200">{campaignData.customEquipment.length}</span></div><div className="mt-4 space-y-2">{campaignData.customEquipment.map((item) => <button type="button" key={item.id} onClick={() => onOpenItem(item.id)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-white/5 bg-slate-950/45 p-3 text-left hover:border-amber-400/25"><span><span className="block font-black text-slate-100">{item.name}</span><span className="mt-1 block text-xs text-slate-500">{item.category} • {item.slot}</span></span><span className="text-amber-300">Open →</span></button>)}{campaignData.customEquipment.length === 0 && <p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">No custom items yet.</p>}</div></section></div>
  </div>;
}
